# This file exists within 'human-friendly_pedantic-timedelta' aka 'pedantic_timedelta':
#
#   https://github.com/hotoffthehamster/human-friendly_pedantic-timedelta

version: 2

python:
  version: 3.7
  install:
     - method: pip
       path: .

