# Travis CI config.
#
#   https://travis-ci.org/hotoffthehamster/human-friendly_pedantic-timedelta

language: python

matrix:
  include:
    # 2019-02-16: What, no 3.7 on Travis-ci.org?
    #- python: '3.7'
    #  env: TOXENV=py37
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.4'
      env: TOXENV=py34
    - python: '2.7'
      env: TOXENV=py27

install: pip install tox

script: tox

notifications:
  email: false

