# Config file for automatic testing at travis-ci.org

language: python

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=py37

install: pip install tox

script: tox

notifications:
  email: false

